pool:
  name: Arm64
  vmImage: 'ubuntu-22.04'

trigger:
- main
resources:
- repo: self
variables:
  imagePullSecret: 'regcred'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:


    - task: Kubernetes@1
      displayName: Deploy to Kubernetes cluster
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: K8SOracleCloud
        namespace: 'jaeger'
        command: 'apply'
        arguments: '-f k8s/'
        force: true
