apiVersion: v1
kind: Secret
metadata:
  name: jaeger-secrets
  namespace: jaeger
type: Opaque
data:
  JAEGER_USER: "YWRtaW4=" # echo -n 'admin' | base64
  JAEGER_PASSWORD: "cGFzc3dvcmQ=" # echo -n 'password' | base64
